server:
  port: 4005

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:4004
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
            - JwtValidation

        - id: patient-service
          uri: http://localhost:4000
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - StripPrefix=3
            - JwtValidation

        - id: doctor-service
          uri: http://localhost:4002
          predicates:
            - Path=/api/v1/doctors/**
          filters:
            - StripPrefix=3
            - JwtValidation

        - id: appointment-service
          uri: http://localhost:4003
          predicates:
            - Path=/api/v1/appointments/**
          filters:
            - StripPrefix=3
            - JwtValidation

      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

auth:
  service:
    url: http://localhost:4004